#!/bin/bash

function error() {
	helpMessage="Check help for more information."
	if [[ -u $2 || $2 = true ]]; then
		helpMessage=""
	fi
	echo "E: $1 $helpMessage"
	exit 1
}

function getDockerID() {
	echo $(docker ps -q --filter "name=$1")
}

read -p "Install docker? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
	echo "Installing docker..."
	wget -qO- https://get.docker.com/ | sh
	echo "Installing python-pip..."
	if [ $(sudo apt-get install -y python-pip) = "0" ]; then
		echo "Installing docker-compose..."
		sudo pip install docker-compose
	else
		error "Installing python-pip failed! (apt-get returned non 0 exit code)"
	fi
fi

read -p "Let's encrypt email: " EMAIL
export LETSENCRYPT_EMAIL=$EMAIL
